### PR TITLE
Update TicketTaskManagerWindowController.swift

### PR DESCRIPTION
**Pull request by Mqhong**
Call can throw, but it is not marked with 'try' and the error is not handle

### CODE REVIEW

**Comment by fancymax** [comment]
what's your  Xcode Version?

**Comment by Mqhong** [comment]
Version 9.2 (9C40b)

**Comment by DreamYu** [comment]
let json = try!JSON(data: dataFromString) 
试试这个

**Comment by fancymax** [comment]
has Merge 
#210

**Pull request closed without merging**
